### ISSUE TITLE
npm run dev 总是缺少依赖

### ISSUE THREAD

**Issue by wsqy** [zhangyanzt/vue-apicloud#9]
`> cross-env NODE_ENV=development webpack-dev-server --inline --hot

module.js:471
    throw err;
    ^

Error: Cannot find module 'balanced-match'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)`

安装完缺少的依赖还是会说少另一个   一直安装了二三十个之后放弃了

**Comment by zhangyanzt** [comment]
你没有执行npm install嘛？
